export enum ScoresSortOrder {
  USERNAME = "USERNAME",
  USERNAME_REVERSE = "USERNAME_REVERSE",
  SCORE = "SCORE",
  SCORE_REVERSE = "SCORE_REVERSE",
  DATE = "DATE",
  DATE_REVERSE = "DATE_REVERSE",
}
